export let reviews = [
  {
    id: "0",
    userId: "0",
    score: 1,
    place: "0",
    rating: 2,
    date: new Date("October 13, 1996 05:35:32"),
    modifiedDate: new Date("October 13, 1999 05:35:32"),
    text: `1This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!`,
    tags: "#da#nicePlace#bestFood#testTag#Vegan#Bio#restingPlace",
    images: ["0", "1", "2"],
    nrRatings: 20,
    usersThatScored: ["0", "1"]
  },
  {
    id: "1",
    userId: "3",
    score: 19,
    place: "0",
    rating: 3,
    modifiedDate: new Date("October 13, 2016 05:35:32"),
    date: new Date("2014-09-15 09:00:00"),
    text: `2This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!`,
    tags: "#da#nicePlace#bestFood#testTag#Vegan#Bio#restingPlace",
    images: ["0", "1", "2"],
    nrRatings: 20,
    usersThatScored: ["0", "1"]
  },
  {
    id: "2",
    score: -6,
    userId: "1",
    place: "0",
    rating: 2,
    modifiedDate: new Date("October 13, 2017 05:35:32"),
    date: new Date("2014-09-15 09:00:00"),
    text: `3This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!`,
    tags: "#da#nicePlace#bestFood#testTag#Vegan#Bio#restingPlace",
    images: ["0", "4"],
    nrRatings: 20,
    usersThatScored: ["0", "1"]
  },
  {
    id: "3",
    score: 22,
    userId: "3",
    place: "1",
    rating: 1,
    modifiedDate: new Date("October 13, 2019 05:35:32"),
    date: new Date("2014-09-15 09:00:00"),
    text: `4This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!`,
    tags: "#da#nicePlace#bestFood#testTag#Vegan#Bio#restingPlace",
    images: ["1", "4", "2"],
    nrRatings: 20,
    usersThatScored: ["0", "1"]
  },
  {
    id: "4",
    score: 6,
    userId: "4",
    place: "2",
    rating: 5,
    modifiedDate: new Date("October 13, 2018 05:35:32"),
    date: new Date("2014-09-15 09:00:00"),
    text: `5This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!This place was awesome I'dd really want to visit it very soon, I hope it will happen GREAT!`,
    tags: "#da#nicePlace#bestFood#testTag#Vegan#Bio#restingPlace",
    nrRatings: 20,
    usersThatScored: ["0", "1"]
  }
];
