export const SearchPlaceholder = "Search books";
export const ShowMoreCaption = "Show more";
export const ShowLessCaption = "Show less";
export const BookShelvesCaption = "Book shelves";
export const CurrentlyReadingCaption = "Currently Reading";
export const SeeMoreCaption = "See more";
export const AddBookCaption = "Add a book";
export const ViewAllBooksCaption = "View all books";
export const MyBooksCaption = "My Books";